#!/usr/bin/env python3
"""Agentic Planning Kit v3 control plane (Python standard library only)."""

from __future__ import annotations

import argparse
import datetime as dt
import hashlib
import json
import math
import os
import posixpath
from pathlib import Path, PurePosixPath
import re
import subprocess
import sys
import tempfile
from dataclasses import dataclass
from typing import Any, Iterable, Sequence


TOOL_VERSION = "3.0.0"
SCHEMA_BY_ARTIFACT = {
    "contract": "contract.schema.json",
    "entity_descriptor": "entity-descriptor.schema.json",
    "entity_manifest": "entity-manifest.schema.json",
    "event": "event.schema.json",
    "run_receipt": "run-receipt.schema.json",
    "map_delta": "map-delta.schema.json",
    "catalog_item": "catalog-item.schema.json",
    "reconciliation_receipt": "reconciliation-receipt.schema.json",
    "legacy_import": "legacy-import.schema.json",
}
ENTITY_COLLECTION = {
    "feature": "features",
    "analysis": "analyses",
    "project": "projects",
}
ENTITY_PREFIX = {"feature": "ftr_", "analysis": "ana_", "project": "prj_"}
TERMINAL_STATES = {"COMPLETED", "CANCELLED", "SUPERSEDED"}
STATE_TRANSITIONS = {
    "PLANNED": {
        "PLANNED",
        "ACTIVE",
        "BLOCKED",
        "RECONCILIATION_PENDING",
        "COMPLETED",
        "CANCELLED",
        "SUPERSEDED",
    },
    "ACTIVE": {
        "ACTIVE",
        "BLOCKED",
        "PARTIALLY_MERGED",
        "RECONCILIATION_PENDING",
        "COMPLETED",
        "CANCELLED",
        "SUPERSEDED",
    },
    "BLOCKED": {
        "ACTIVE",
        "PARTIALLY_MERGED",
        "RECONCILIATION_PENDING",
        "CANCELLED",
        "SUPERSEDED",
    },
    "PARTIALLY_MERGED": {
        "ACTIVE",
        "BLOCKED",
        "RECONCILIATION_PENDING",
        "COMPLETED",
        "CANCELLED",
    },
    "RECONCILIATION_PENDING": {
        "ACTIVE",
        "BLOCKED",
        "COMPLETED",
        "CANCELLED",
    },
    "UNKNOWN_LEGACY": {"PLANNED", "ACTIVE", "BLOCKED", "CANCELLED", "SUPERSEDED"},
    "COMPLETED": set(),
    "CANCELLED": set(),
    "SUPERSEDED": set(),
}
CATALOG_ORDER = [
    "repository",
    "subproject",
    "command",
    "resource",
    "gate",
    "contract",
    "store",
    "seam",
    "recipe",
    "convention",
    "practice",
    "policy",
    "unknown",
]
CATALOG_HEADINGS = {
    "repository": "Repositories",
    "subproject": "Subprojects",
    "command": "Commands",
    "resource": "Shared resources",
    "gate": "Validation gates",
    "contract": "Canonical contracts",
    "store": "Data stores",
    "seam": "Integration seams",
    "recipe": "Recipes",
    "convention": "Conventions",
    "practice": "Engineering practices",
    "policy": "Policies and guardrails",
    "unknown": "Unknown facts",
}
MANAGED_BEGIN = "<!-- agentic-routes:begin — generated by Agentic Planning Kit v3; do not edit this block. -->"
MANAGED_END = "<!-- agentic-routes:end -->"


@dataclass(frozen=True, order=True)
class Issue:
    code: str
    path: str
    message: str

    def line(self) -> str:
        location = self.path or "."
        return f"ERROR {self.code} {location}: {self.message}"


@dataclass(frozen=True)
class Artifact:
    path: Path
    relative_path: str
    expected_type: str
    data: dict[str, Any]


class DuplicateKeyError(ValueError):
    pass


def _pairs_without_duplicates(pairs: list[tuple[str, Any]]) -> dict[str, Any]:
    result: dict[str, Any] = {}
    for key, value in pairs:
        if key in result:
            raise DuplicateKeyError(f"duplicate JSON key {key!r}")
        result[key] = value
    return result


def load_json(path: Path) -> Any:
    with path.open("r", encoding="utf-8-sig", newline="") as handle:
        return json.load(
            handle,
            object_pairs_hook=_pairs_without_duplicates,
            parse_constant=lambda token: (_ for _ in ()).throw(
                ValueError(f"non-finite JSON number {token}")
            ),
        )


def canonical_json_bytes(value: Any) -> bytes:
    return (
        json.dumps(value, ensure_ascii=False, sort_keys=True, separators=(",", ":"), allow_nan=False)
        + "\n"
    ).encode("utf-8")


def sha256_bytes(value: bytes) -> str:
    return hashlib.sha256(value).hexdigest()


def legacy_source_sha256(path: Path, source_kind: str) -> str:
    if path.is_symlink():
        raise ValueError("legacy source may not be a symlink")
    if source_kind == "file":
        if not path.is_file():
            raise ValueError("legacy file source does not exist")
        return sha256_bytes(path.read_bytes())
    if source_kind != "tree" or not path.is_dir():
        raise ValueError("legacy tree source does not exist")
    entries: list[dict[str, str]] = []
    for child in sorted(path.rglob("*"), key=lambda item: item.as_posix()):
        if child.is_symlink():
            raise ValueError(f"legacy tree contains symlink {child.relative_to(path).as_posix()}")
        if child.is_file():
            entries.append(
                {
                    "path": child.relative_to(path).as_posix(),
                    "sha256": sha256_bytes(child.read_bytes()),
                }
            )
    return sha256_bytes(canonical_json_bytes(entries))


def _json_pointer(root: Any, pointer: str) -> Any:
    current = root
    if pointer in ("", "#"):
        return current
    raw = pointer[1:] if pointer.startswith("#") else pointer
    if not raw.startswith("/"):
        raise ValueError(f"invalid JSON pointer {pointer!r}")
    for part in raw[1:].split("/"):
        part = part.replace("~1", "/").replace("~0", "~")
        if isinstance(current, list):
            current = current[int(part)]
        else:
            current = current[part]
    return current


class SchemaStore:
    """Small Draft 2020-12 subset sufficient for the kit's closed schemas."""

    def __init__(self, directory: Path):
        self.directory = directory
        self._cache: dict[Path, Any] = {}

    def load(self, name_or_path: str | Path) -> tuple[Path, Any]:
        path = Path(name_or_path)
        if not path.is_absolute():
            path = self.directory / path
        path = path.resolve()
        if path not in self._cache:
            self._cache[path] = load_json(path)
        return path, self._cache[path]

    def validate(self, value: Any, schema_name: str, artifact_path: str) -> list[Issue]:
        schema_path, schema = self.load(schema_name)
        messages: list[str] = []
        self._check(schema, value, "$", schema_path, schema, messages)
        return [Issue("SCHEMA_INVALID", artifact_path, message) for message in messages]

    def _resolve_ref(
        self, reference: str, document_path: Path, document_root: Any
    ) -> tuple[Any, Path, Any]:
        if reference.startswith("#"):
            return _json_pointer(document_root, reference), document_path, document_root
        file_part, marker, fragment = reference.partition("#")
        target_path, target_root = self.load((document_path.parent / file_part).resolve())
        target = _json_pointer(target_root, f"#{fragment}" if marker else "#")
        return target, target_path, target_root

    @staticmethod
    def _is_type(value: Any, type_name: str) -> bool:
        if type_name == "null":
            return value is None
        if type_name == "object":
            return isinstance(value, dict)
        if type_name == "array":
            return isinstance(value, list)
        if type_name == "string":
            return isinstance(value, str)
        if type_name == "boolean":
            return isinstance(value, bool)
        if type_name == "integer":
            return isinstance(value, int) and not isinstance(value, bool)
        if type_name == "number":
            return isinstance(value, (int, float)) and not isinstance(value, bool)
        return False

    def _check(
        self,
        schema: Any,
        value: Any,
        pointer: str,
        document_path: Path,
        document_root: Any,
        messages: list[str],
    ) -> None:
        if isinstance(schema, bool):
            if not schema:
                messages.append(f"{pointer}: value is forbidden")
            return
        if "$ref" in schema:
            target, target_path, target_root = self._resolve_ref(
                schema["$ref"], document_path, document_root
            )
            self._check(target, value, pointer, target_path, target_root, messages)
            return

        if "const" in schema and value != schema["const"]:
            messages.append(f"{pointer}: expected constant {schema['const']!r}")
        if "enum" in schema and value not in schema["enum"]:
            messages.append(f"{pointer}: value {value!r} is not in the allowed set")

        declared_type = schema.get("type")
        if declared_type is not None:
            type_names = declared_type if isinstance(declared_type, list) else [declared_type]
            if not any(self._is_type(value, type_name) for type_name in type_names):
                messages.append(f"{pointer}: expected type {' or '.join(type_names)}")
                return

        if "allOf" in schema:
            for branch in schema["allOf"]:
                self._check(branch, value, pointer, document_path, document_root, messages)
        if "anyOf" in schema:
            branch_messages: list[list[str]] = []
            for branch in schema["anyOf"]:
                current: list[str] = []
                self._check(branch, value, pointer, document_path, document_root, current)
                branch_messages.append(current)
            if all(current for current in branch_messages):
                messages.append(f"{pointer}: value does not match any allowed schema")
        if "oneOf" in schema:
            valid_count = 0
            for branch in schema["oneOf"]:
                current = []
                self._check(branch, value, pointer, document_path, document_root, current)
                if not current:
                    valid_count += 1
            if valid_count != 1:
                messages.append(f"{pointer}: value must match exactly one schema")

        if isinstance(value, dict):
            required = schema.get("required", [])
            for name in required:
                if name not in value:
                    messages.append(f"{pointer}: missing required property {name!r}")
            properties = schema.get("properties", {})
            for name, child in value.items():
                child_pointer = f"{pointer}/{name.replace('~', '~0').replace('/', '~1')}"
                if name in properties:
                    self._check(
                        properties[name],
                        child,
                        child_pointer,
                        document_path,
                        document_root,
                        messages,
                    )
                elif schema.get("additionalProperties") is False:
                    messages.append(f"{child_pointer}: additional property is not allowed")
                elif isinstance(schema.get("additionalProperties"), dict):
                    self._check(
                        schema["additionalProperties"],
                        child,
                        child_pointer,
                        document_path,
                        document_root,
                        messages,
                    )
            min_properties = schema.get("minProperties")
            if min_properties is not None and len(value) < min_properties:
                messages.append(f"{pointer}: expected at least {min_properties} properties")

        if isinstance(value, list):
            if "minItems" in schema and len(value) < schema["minItems"]:
                messages.append(f"{pointer}: expected at least {schema['minItems']} items")
            if "maxItems" in schema and len(value) > schema["maxItems"]:
                messages.append(f"{pointer}: expected at most {schema['maxItems']} items")
            if schema.get("uniqueItems"):
                seen: set[bytes] = set()
                for item in value:
                    marker = canonical_json_bytes(item)
                    if marker in seen:
                        messages.append(f"{pointer}: array items must be unique")
                        break
                    seen.add(marker)
            if "items" in schema:
                for index, item in enumerate(value):
                    self._check(
                        schema["items"],
                        item,
                        f"{pointer}/{index}",
                        document_path,
                        document_root,
                        messages,
                    )

        if isinstance(value, str):
            if "minLength" in schema and len(value) < schema["minLength"]:
                messages.append(f"{pointer}: string is shorter than {schema['minLength']}")
            if "maxLength" in schema and len(value) > schema["maxLength"]:
                messages.append(f"{pointer}: string is longer than {schema['maxLength']}")
            if "pattern" in schema and re.search(schema["pattern"], value) is None:
                messages.append(f"{pointer}: string does not match {schema['pattern']!r}")
            if schema.get("format") == "date-time" and not _valid_datetime(value):
                messages.append(f"{pointer}: expected an RFC 3339 date-time with timezone")

        if isinstance(value, (int, float)) and not isinstance(value, bool):
            if not math.isfinite(value):
                messages.append(f"{pointer}: number must be finite")
            if "minimum" in schema and value < schema["minimum"]:
                messages.append(f"{pointer}: number is less than {schema['minimum']}")


def _valid_datetime(value: str) -> bool:
    try:
        parsed = dt.datetime.fromisoformat(value.replace("Z", "+00:00"))
    except ValueError:
        return False
    return parsed.tzinfo is not None


def _datetime_key(value: str) -> tuple[dt.datetime, str]:
    parsed = dt.datetime.fromisoformat(value.replace("Z", "+00:00"))
    return parsed.astimezone(dt.timezone.utc), value


def _relative(root: Path, path: Path) -> str:
    return path.resolve().relative_to(root.resolve()).as_posix()


def _path_is_safe(value: str, *, allow_dot: bool = False) -> bool:
    if not value or "\\" in value or "\x00" in value:
        return False
    if value == ".":
        return allow_dot
    if value.startswith("/") or re.match(r"^[A-Za-z]:", value):
        return False
    raw_parts = value.split("/")
    if any(part in ("", ".", "..") for part in raw_parts):
        return False
    return PurePosixPath(value).as_posix() == value


def _under_root(root: Path, path: Path) -> bool:
    try:
        path.resolve().relative_to(root.resolve())
        return True
    except ValueError:
        return False


def _artifact_patterns() -> list[tuple[str, str]]:
    patterns: list[tuple[str, str]] = []
    for collection in ("features", "analyses", "projects"):
        base = f".agentic_planning/{collection}"
        patterns.extend(
            [
                (f"{base}/*/descriptor.json", "entity_descriptor"),
                (f"{base}/*/plans/*/manifest.json", "entity_manifest"),
                (f"{base}/*/events/*.json", "event"),
                (f"{base}/*/runs/*/*.json", "run_receipt"),
                (f"{base}/*/map-deltas/*.json", "map_delta"),
            ]
        )
    patterns.extend(
        [
            (".agentic_planning/catalog/**/*.json", "catalog_item"),
            (".agentic_planning/reconciliations/*/receipt.json", "reconciliation_receipt"),
            (".agentic_planning/imports/legacy/*/import.json", "legacy_import"),
        ]
    )
    return patterns


def discover_artifacts(root: Path, explicit_paths: Sequence[str] | None = None) -> tuple[list[Artifact], list[Issue]]:
    artifacts: list[Artifact] = []
    issues: list[Issue] = []
    candidates: dict[Path, str] = {}
    contract_path = root / ".agentic_planning" / "CONTRACT.json"

    if explicit_paths:
        for raw in explicit_paths:
            candidate = Path(raw)
            path = candidate if candidate.is_absolute() else root / candidate
            if not _under_root(root, path):
                issues.append(Issue("PATH_OUTSIDE_ROOT", str(raw), "artifact is outside the workspace"))
                continue
            candidates[path.resolve()] = ""
    else:
        candidates[contract_path.resolve()] = "contract"
        for pattern, expected_type in _artifact_patterns():
            for path in root.glob(pattern):
                if path.is_file():
                    candidates[path.resolve()] = expected_type

    for path, expected_type in sorted(candidates.items(), key=lambda pair: pair[0].as_posix()):
        relative_path = _relative(root, path) if _under_root(root, path) else str(path)
        if not path.is_file():
            issues.append(Issue("ARTIFACT_MISSING", relative_path, "required artifact does not exist"))
            continue
        try:
            value = load_json(path)
        except (OSError, UnicodeError, json.JSONDecodeError, DuplicateKeyError, ValueError) as exc:
            issues.append(Issue("JSON_INVALID", relative_path, str(exc)))
            continue
        if not isinstance(value, dict):
            issues.append(Issue("ARTIFACT_INVALID", relative_path, "top-level JSON value must be an object"))
            continue
        actual_type = value.get("artifact_type")
        if not expected_type:
            expected_type = actual_type if isinstance(actual_type, str) else ""
        if expected_type not in SCHEMA_BY_ARTIFACT:
            issues.append(
                Issue("ARTIFACT_TYPE_UNKNOWN", relative_path, f"unknown artifact_type {actual_type!r}")
            )
            continue
        artifacts.append(Artifact(path, relative_path, expected_type, value))
    return artifacts, issues


def _by_type(artifacts: Iterable[Artifact], artifact_type: str) -> list[Artifact]:
    return [artifact for artifact in artifacts if artifact.expected_type == artifact_type]


def _identity_path_issues(artifact: Artifact) -> list[Issue]:
    data = artifact.data
    rel = artifact.relative_path
    parts = PurePosixPath(rel).parts
    issues: list[Issue] = []
    if artifact.expected_type == "contract":
        if rel != ".agentic_planning/CONTRACT.json":
            issues.append(Issue("PATH_ID_MISMATCH", rel, "contract must be .agentic_planning/CONTRACT.json"))
        return issues
    if artifact.expected_type == "catalog_item":
        if PurePosixPath(rel).name != f"{data.get('item_id')}.json":
            issues.append(Issue("PATH_ID_MISMATCH", rel, "catalog filename must equal <item_id>.json"))
        if len(parts) < 4 or parts[-2] != data.get("kind"):
            issues.append(Issue("PATH_KIND_MISMATCH", rel, "catalog path must be catalog/<kind>/<item_id>.json"))
        return issues
    if artifact.expected_type == "reconciliation_receipt":
        if len(parts) < 4 or parts[-2] != data.get("receipt_id"):
            issues.append(Issue("PATH_ID_MISMATCH", rel, "receipt directory must equal receipt_id"))
        return issues
    if artifact.expected_type == "legacy_import":
        if (
            len(parts) != 5
            or parts[:3] != (".agentic_planning", "imports", "legacy")
            or parts[-2] != data.get("entity_id")
            or parts[-1] != "import.json"
        ):
            issues.append(
                Issue("PATH_ID_MISMATCH", rel, "legacy sidecar must be imports/legacy/<entity_id>/import.json")
            )
        prefix = ENTITY_PREFIX.get(data.get("kind"))
        if prefix and isinstance(data.get("entity_id"), str) and not str(data.get("entity_id")).startswith(prefix):
            issues.append(Issue("ID_KIND_MISMATCH", rel, "legacy entity ID prefix does not match kind"))
        return issues
    if len(parts) < 3 or parts[0] != ".agentic_planning":
        issues.append(Issue("PATH_ID_MISMATCH", rel, "entity artifact is outside a native entity tree"))
        return issues
    entity_id = data.get("entity_id")
    entity_dir = parts[2]
    if not isinstance(entity_id, str) or not entity_dir.startswith(f"{entity_id}--"):
        issues.append(Issue("PATH_ID_MISMATCH", rel, "entity directory must start with <entity_id>--"))
    if artifact.expected_type == "entity_descriptor":
        expected_collection = ENTITY_COLLECTION.get(data.get("kind"))
        if expected_collection and parts[1] != expected_collection:
            issues.append(Issue("PATH_KIND_MISMATCH", rel, "descriptor kind does not match its collection"))
        expected_dir = f"{entity_id}--{data.get('slug')}"
        if entity_dir != expected_dir:
            issues.append(Issue("PATH_ID_MISMATCH", rel, "descriptor directory must be <entity_id>--<slug>"))
        prefix = ENTITY_PREFIX.get(data.get("kind"))
        if prefix and isinstance(entity_id, str) and not entity_id.startswith(prefix):
            issues.append(Issue("ID_KIND_MISMATCH", rel, "entity ID prefix does not match descriptor kind"))
    elif artifact.expected_type == "entity_manifest":
        if len(parts) < 6 or parts[-3] != "plans" or parts[-2] != data.get("revision_id"):
            issues.append(Issue("PATH_ID_MISMATCH", rel, "manifest path must contain plans/<revision_id>"))
    elif artifact.expected_type == "event":
        if PurePosixPath(rel).stem != data.get("event_id"):
            issues.append(Issue("PATH_ID_MISMATCH", rel, "event filename must equal event_id"))
    elif artifact.expected_type == "run_receipt":
        if (
            len(parts) < 6
            or PurePosixPath(rel).stem != data.get("attempt_id")
            or parts[-2] != data.get("run_id")
            or parts[-3] != "runs"
        ):
            issues.append(
                Issue(
                    "PATH_ID_MISMATCH",
                    rel,
                    "run path must be runs/<run_id>/<attempt_id>.json; step_id is stored in the receipt",
                )
            )
    elif artifact.expected_type == "map_delta":
        if PurePosixPath(rel).stem != data.get("delta_id"):
            issues.append(Issue("PATH_ID_MISMATCH", rel, "map-delta filename must equal delta_id"))
    return issues


def _duplicate_id_issues(artifacts: Sequence[Artifact]) -> list[Issue]:
    fields = {
        "entity_descriptor": ["entity_id"],
        "entity_manifest": ["revision_id"],
        "event": ["event_id"],
        # A logical run may have several attempts. attempt_id is globally unique;
        # the (run_id, attempt_id) pair is also enforced by its identity path.
        "run_receipt": ["attempt_id"],
        "map_delta": ["delta_id"],
        "catalog_item": ["item_id"],
        "reconciliation_receipt": ["receipt_id"],
        "legacy_import": ["entity_id"],
    }
    issues: list[Issue] = []
    seen: dict[tuple[str, str], str] = {}
    for artifact in artifacts:
        for field in fields.get(artifact.expected_type, []):
            value = artifact.data.get(field)
            if not isinstance(value, str):
                continue
            key = (field, value)
            if key in seen:
                issues.append(
                    Issue(
                        "DUPLICATE_ID",
                        artifact.relative_path,
                        f"{field} {value!r} already appears in {seen[key]}",
                    )
                )
            else:
                seen[key] = artifact.relative_path
    entity_seen: dict[str, str] = {}
    for artifact in [*_by_type(artifacts, "entity_descriptor"), *_by_type(artifacts, "legacy_import")]:
        entity_id = str(artifact.data.get("entity_id"))
        if entity_id in entity_seen:
            issues.append(
                Issue("DUPLICATE_ID", artifact.relative_path, f"entity_id {entity_id} also appears at {entity_seen[entity_id]}")
            )
        else:
            entity_seen[entity_id] = artifact.relative_path
    return issues


def _event_chain(
    entity_id: str, event_artifacts: Sequence[Artifact], issues: list[Issue] | None = None
) -> list[Artifact]:
    """Return the causal chain. Timestamps are display metadata, never ordering authority."""
    events = [item for item in event_artifacts if item.data.get("entity_id") == entity_id]
    if not events:
        return []
    by_id = {str(item.data.get("event_id")): item for item in events}
    roots = [item for item in events if item.data.get("parent_event_id") is None]
    if len(roots) != 1:
        if issues is not None:
            issues.append(
                Issue(
                    "EVENT_CAS_CONFLICT",
                    roots[0].relative_path if roots else events[0].relative_path,
                    f"entity must have exactly one root event; found {len(roots)}",
                )
            )
        return sorted(events, key=lambda item: str(item.data.get("event_id")))
    children: dict[str, list[Artifact]] = {}
    for event in events:
        parent = event.data.get("parent_event_id")
        if parent is None:
            continue
        if str(parent) not in by_id:
            if issues is not None:
                issues.append(Issue("EVENT_CHAIN_INVALID", event.relative_path, f"parent event {parent} does not exist"))
            continue
        children.setdefault(str(parent), []).append(event)
    chain: list[Artifact] = []
    seen: set[str] = set()
    current = roots[0]
    while True:
        event_id = str(current.data.get("event_id"))
        if event_id in seen:
            if issues is not None:
                issues.append(Issue("EVENT_CHAIN_INVALID", current.relative_path, "event chain contains a cycle"))
            break
        seen.add(event_id)
        chain.append(current)
        next_events = children.get(event_id, [])
        if len(next_events) > 1:
            if issues is not None:
                issues.append(
                    Issue(
                        "EVENT_CAS_CONFLICT",
                        next_events[0].relative_path,
                        f"event {event_id} has {len(next_events)} concurrent children",
                    )
                )
            break
        if not next_events:
            break
        current = next_events[0]
    if len(seen) != len(events) and issues is not None:
        for orphan in events:
            if str(orphan.data.get("event_id")) not in seen:
                issues.append(Issue("EVENT_CHAIN_INVALID", orphan.relative_path, "event is outside the single causal chain"))
    return chain


def _event_state(
    entity_id: str, event_artifacts: Sequence[Artifact], issues: list[Issue] | None = None
) -> str:
    chain = _event_chain(entity_id, event_artifacts, issues)
    if not chain:
        return "PLANNED"
    previous: Artifact | None = None
    for event in chain:
        data = event.data
        if previous is None:
            if data.get("expected_state") is not None:
                if issues is not None:
                    issues.append(Issue("EVENT_CHAIN_INVALID", event.relative_path, "root event must have null expected state"))
            if data.get("state") not in {"PLANNED", "UNKNOWN_LEGACY"}:
                if issues is not None:
                    issues.append(
                        Issue("EVENT_TRANSITION_INVALID", event.relative_path, "first state must be PLANNED or UNKNOWN_LEGACY")
                    )
        else:
            if data.get("expected_state") != previous.data.get("state"):
                if issues is not None:
                    issues.append(
                        Issue(
                            "EVENT_CAS_CONFLICT",
                            event.relative_path,
                            f"expected_state must be {previous.data.get('state')}",
                        )
                    )
            allowed = STATE_TRANSITIONS.get(str(previous.data.get("state")), set())
            if data.get("state") not in allowed:
                if issues is not None:
                    issues.append(
                        Issue(
                            "EVENT_TRANSITION_INVALID",
                            event.relative_path,
                            f"transition {previous.data.get('state')} -> {data.get('state')} is not allowed",
                        )
                    )
        previous = event
    return str(chain[-1].data["state"])


def _reconciliation_receipt_issues(receipts: Sequence[Artifact]) -> list[Issue]:
    if not receipts:
        return []
    issues: list[Issue] = []
    by_id = {str(item.data.get("receipt_id")): item for item in receipts}
    roots: list[Artifact] = []
    children: dict[str, list[Artifact]] = {}
    for receipt in receipts:
        parent = receipt.data.get("parent_receipt_id")
        if parent is None:
            roots.append(receipt)
        elif parent not in by_id:
            issues.append(
                Issue("RECEIPT_CHAIN_INVALID", receipt.relative_path, f"missing parent receipt {parent}")
            )
        else:
            children.setdefault(str(parent), []).append(receipt)
        input_paths = [str(item.get("path")) for item in receipt.data.get("input_hashes", [])]
        output_paths = [str(item.get("path")) for item in receipt.data.get("output_hashes", [])]
        paths = [*input_paths, *output_paths]
        if len(input_paths) != len(set(input_paths)) or len(output_paths) != len(set(output_paths)):
            issues.append(Issue("RECEIPT_INVALID", receipt.relative_path, "path hashes contain duplicates within one side"))
        for path in paths:
            if not _path_is_safe(path):
                issues.append(Issue("PATH_UNSAFE", receipt.relative_path, f"unsafe receipt path {path!r}"))
        if receipt.data.get("status") == "SUCCEEDED" and receipt.data.get("error_codes"):
            issues.append(Issue("RECEIPT_INVALID", receipt.relative_path, "SUCCEEDED receipt must have no error codes"))
    if len(roots) != 1:
        issues.append(
            Issue("RECEIPT_CHAIN_CONFLICT", ".agentic_planning/reconciliations", f"expected one root receipt, found {len(roots)}")
        )
        return issues
    for parent, contenders in children.items():
        if len(contenders) > 1:
            issues.append(
                Issue("RECEIPT_CAS_CONFLICT", contenders[0].relative_path, f"receipt {parent} has {len(contenders)} children")
            )
    visited: set[str] = set()
    current = roots[0]
    while True:
        receipt_id = str(current.data.get("receipt_id"))
        if receipt_id in visited:
            issues.append(Issue("RECEIPT_CHAIN_INVALID", current.relative_path, "receipt cycle detected"))
            break
        visited.add(receipt_id)
        next_items = children.get(receipt_id, [])
        if len(next_items) != 1:
            break
        current = next_items[0]
    if len(visited) != len(receipts):
        issues.append(
            Issue("RECEIPT_CHAIN_CONFLICT", ".agentic_planning/reconciliations", "receipt graph is forked or disconnected")
        )
    return issues


def _current_revision_id(entity_id: str, descriptors: dict[str, Artifact], manifests: Sequence[Artifact], events: Sequence[Artifact]) -> str | None:
    descriptor = descriptors.get(entity_id)
    if descriptor is None:
        return None
    revision = descriptor.data.get("initial_revision_id")
    known = {
        str(item.data.get("revision_id"))
        for item in manifests
        if item.data.get("entity_id") == entity_id
    }
    for event in _event_chain(entity_id, events):
        candidate = event.data.get("revision_id")
        if isinstance(candidate, str) and candidate in known:
            revision = candidate
    return str(revision) if revision is not None else None


def _cross_reference_issues(artifacts: Sequence[Artifact]) -> list[Issue]:
    issues: list[Issue] = []
    descriptors = {item.data.get("entity_id"): item for item in _by_type(artifacts, "entity_descriptor")}
    legacy_imports = {item.data.get("entity_id"): item for item in _by_type(artifacts, "legacy_import")}
    manifests = _by_type(artifacts, "entity_manifest")
    manifests_by_revision = {item.data.get("revision_id"): item for item in manifests}
    events = _by_type(artifacts, "event")
    runs = _by_type(artifacts, "run_receipt")
    runs_by_id: dict[str, list[Artifact]] = {}
    for run in runs:
        runs_by_id.setdefault(str(run.data.get("run_id")), []).append(run)
    catalog = {item.data.get("item_id"): item for item in _by_type(artifacts, "catalog_item")}
    receipts = _by_type(artifacts, "reconciliation_receipt")
    issues.extend(_reconciliation_receipt_issues(receipts))
    receipts_by_id = {str(item.data.get("receipt_id")): item for item in receipts}
    applied_delta_ids: set[str] = set()
    for receipt in receipts:
        if receipt.data.get("status") != "SUCCEEDED":
            if receipt.data.get("applied_delta_ids"):
                issues.append(
                    Issue("RECEIPT_INVALID", receipt.relative_path, "only SUCCEEDED receipts may apply deltas")
                )
            continue
        for delta_id in receipt.data.get("applied_delta_ids", []):
            if delta_id in applied_delta_ids:
                issues.append(
                    Issue("DELTA_APPLIED_TWICE", receipt.relative_path, f"delta {delta_id} appears in more than one receipt")
                )
            applied_delta_ids.add(str(delta_id))

    contracts = _by_type(artifacts, "contract")
    if len(contracts) == 1:
        workspace_root = contracts[0].path.parent.parent
        root_project_id = contracts[0].data.get("root_project_id")
        if root_project_id is not None:
            root_descriptor = descriptors.get(root_project_id)
            if root_descriptor is None:
                issues.append(
                    Issue("REFERENCE_MISSING", contracts[0].relative_path, f"root project {root_project_id} does not exist")
                )
            elif root_descriptor.data.get("kind") != "project":
                issues.append(
                    Issue("REFERENCE_INVALID", contracts[0].relative_path, f"root project {root_project_id} is not a project")
                )

        all_entities = {**legacy_imports, **descriptors}
        for legacy in legacy_imports.values():
            data = legacy.data
            source_path = str(data.get("source_path", ""))
            if not _path_is_safe(source_path) or source_path.startswith(".agentic_planning/imports/"):
                issues.append(Issue("PATH_UNSAFE", legacy.relative_path, f"unsafe legacy source path {source_path!r}"))
            else:
                source = workspace_root / source_path
                if not _under_root(workspace_root, source):
                    issues.append(Issue("PATH_OUTSIDE_ROOT", legacy.relative_path, "legacy source escapes workspace"))
                else:
                    try:
                        actual_hash = legacy_source_sha256(source, str(data.get("source_kind")))
                    except (OSError, ValueError) as exc:
                        issues.append(Issue("LEGACY_SOURCE_INVALID", legacy.relative_path, str(exc)))
                    else:
                        if actual_hash != data.get("source_sha256"):
                            issues.append(Issue("LEGACY_SOURCE_DRIFT", legacy.relative_path, "legacy source bytes changed after import"))
            for source_id in data.get("source_analysis_ids", []):
                source_entity = all_entities.get(source_id)
                if source_entity is None or source_entity.data.get("kind") != "analysis":
                    issues.append(Issue("REFERENCE_MISSING", legacy.relative_path, f"source analysis {source_id} does not exist"))
            for scope in data.get("write_scopes", []):
                if not _path_is_safe(str(scope.get("path", ""))):
                    issues.append(Issue("PATH_UNSAFE", legacy.relative_path, f"unsafe write scope {scope.get('path')!r}"))
            claim_ids = [str(item.get("resource_id")) for item in data.get("resource_claims", [])]
            if len(claim_ids) != len(set(claim_ids)):
                issues.append(Issue("CLAIM_INVALID", legacy.relative_path, "resource_claims contains duplicate resource IDs"))
            for claim in data.get("resource_claims", []):
                mode = claim.get("mode")
                isolation_key = claim.get("isolation_key")
                if mode == "isolated" and not isolation_key:
                    issues.append(Issue("CLAIM_INVALID", legacy.relative_path, "isolated claim requires isolation_key"))
                if mode != "isolated" and isolation_key is not None:
                    issues.append(Issue("CLAIM_INVALID", legacy.relative_path, "only isolated claims may set isolation_key"))

    for descriptor in descriptors.values():
        data = descriptor.data
        initial = data.get("initial_revision_id")
        if initial is not None:
            manifest = manifests_by_revision.get(initial)
            if manifest is None:
                issues.append(Issue("REFERENCE_MISSING", descriptor.relative_path, f"initial revision {initial} does not exist"))
            elif manifest.data.get("entity_id") != data.get("entity_id"):
                issues.append(Issue("REFERENCE_MISMATCH", descriptor.relative_path, "initial revision belongs to another entity"))
        for source_id in data.get("source_analysis_ids", []):
            source = descriptors.get(source_id) or legacy_imports.get(source_id)
            if source is None or source.data.get("kind") != "analysis":
                issues.append(Issue("REFERENCE_MISSING", descriptor.relative_path, f"source analysis {source_id} does not exist"))

    for manifest in manifests:
        data = manifest.data
        if data.get("entity_id") not in descriptors:
            issues.append(Issue("REFERENCE_MISSING", manifest.relative_path, "manifest entity descriptor does not exist"))
        for dependency in data.get("depends_on", []):
            if dependency == data.get("entity_id"):
                issues.append(Issue("DEPENDENCY_INVALID", manifest.relative_path, "entity cannot depend on itself"))
            elif dependency not in descriptors:
                issues.append(Issue("REFERENCE_MISSING", manifest.relative_path, f"dependency {dependency} does not exist"))
        for base in data.get("planning_base", []):
            if not _path_is_safe(str(base.get("path", "")), allow_dot=True):
                issues.append(Issue("PATH_UNSAFE", manifest.relative_path, f"unsafe repository path {base.get('path')!r}"))
        for map_input in data.get("map_inputs", []):
            item = catalog.get(map_input.get("item_id"))
            if item is None:
                issues.append(Issue("REFERENCE_MISSING", manifest.relative_path, f"map input {map_input.get('item_id')} does not exist"))
            elif sha256_bytes(canonical_json_bytes(item.data)) != map_input.get("sha256"):
                issues.append(Issue("STALE_MAP_CLAIM", manifest.relative_path, f"map input {map_input.get('item_id')} hash changed"))
        map_input_ids = [str(item.get("item_id")) for item in data.get("map_inputs", [])]
        if len(map_input_ids) != len(set(map_input_ids)):
            issues.append(Issue("MANIFEST_INVALID", manifest.relative_path, "map_inputs contains duplicate item IDs"))
        for scope in data.get("write_scopes", []):
            if not _path_is_safe(str(scope.get("path", ""))):
                issues.append(Issue("PATH_UNSAFE", manifest.relative_path, f"unsafe write scope {scope.get('path')!r}"))
        for claim in data.get("resource_claims", []):
            mode = claim.get("mode")
            isolation_key = claim.get("isolation_key")
            if mode == "isolated" and not isolation_key:
                issues.append(Issue("CLAIM_INVALID", manifest.relative_path, "isolated claim requires isolation_key"))
            if mode != "isolated" and isolation_key is not None:
                issues.append(Issue("CLAIM_INVALID", manifest.relative_path, "only isolated claims may set isolation_key"))
        claim_ids = [str(item.get("resource_id")) for item in data.get("resource_claims", [])]
        if len(claim_ids) != len(set(claim_ids)):
            issues.append(Issue("CLAIM_INVALID", manifest.relative_path, "resource_claims contains duplicate resource IDs"))

    for event in events:
        data = event.data
        if data.get("entity_id") not in descriptors:
            issues.append(Issue("REFERENCE_MISSING", event.relative_path, "event entity descriptor does not exist"))
        revision = data.get("revision_id")
        if revision is not None and revision not in manifests_by_revision:
            issues.append(Issue("REFERENCE_MISSING", event.relative_path, f"revision {revision} does not exist"))
        run_id = data.get("run_id")
        if run_id is not None and str(run_id) not in runs_by_id:
            issues.append(Issue("REFERENCE_MISSING", event.relative_path, f"run {run_id} does not exist"))
        receipt_id = data.get("reconciliation_receipt_id")
        if data.get("event_type") == "RECONCILED":
            receipt = receipts_by_id.get(str(receipt_id)) if receipt_id is not None else None
            if receipt is None or receipt.data.get("status") != "SUCCEEDED":
                issues.append(
                    Issue("REFERENCE_MISSING", event.relative_path, "RECONCILED event requires a successful receipt")
                )
            else:
                event_hash = sha256_bytes(event.path.read_bytes())
                bound_hash = next(
                    (
                        item.get("sha256")
                        for item in receipt.data.get("output_hashes", [])
                        if item.get("path") == event.relative_path
                    ),
                    None,
                )
                if bound_hash != event_hash:
                    issues.append(
                        Issue("RECEIPT_BINDING_INVALID", event.relative_path, "successful receipt does not hash this event")
                    )
        elif receipt_id is not None:
            issues.append(
                Issue("EVENT_INVALID", event.relative_path, "only RECONCILED events may set reconciliation_receipt_id")
            )

    for run in runs:
        data = run.data
        if data.get("entity_id") not in descriptors:
            issues.append(Issue("REFERENCE_MISSING", run.relative_path, "run entity descriptor does not exist"))
        manifest = manifests_by_revision.get(data.get("revision_id"))
        if manifest is None or manifest.data.get("entity_id") != data.get("entity_id"):
            issues.append(Issue("REFERENCE_MISSING", run.relative_path, "run revision does not belong to its entity"))
        if data.get("status") in {"SUCCEEDED", "FAILED", "CANCELLED"} and data.get("finished_at") is None:
            issues.append(Issue("RUN_INVALID", run.relative_path, "terminal run requires finished_at"))
        for output in data.get("artifacts", []):
            if not _path_is_safe(str(output.get("path", ""))):
                issues.append(Issue("PATH_UNSAFE", run.relative_path, f"unsafe artifact path {output.get('path')!r}"))

    for run_id, attempts in runs_by_id.items():
        identities = {
            (item.data.get("entity_id"), item.data.get("revision_id"), item.data.get("step_id"))
            for item in attempts
        }
        if len(identities) != 1:
            issues.append(Issue("RUN_ID_COLLISION", attempts[0].relative_path, f"logical run {run_id} changes entity/revision/step"))
        succeeded = [item for item in attempts if item.data.get("status") == "SUCCEEDED"]
        if len(succeeded) > 1:
            issues.append(Issue("RUN_RESULT_CONFLICT", succeeded[0].relative_path, f"logical run {run_id} has multiple successful attempts"))

    for entity_id in descriptors:
        _event_state(str(entity_id), events, issues)

    unapplied_by_item: dict[str, list[Artifact]] = {}
    for delta in _by_type(artifacts, "map_delta"):
        data = delta.data
        if data.get("entity_id") not in descriptors:
            issues.append(Issue("REFERENCE_MISSING", delta.relative_path, "delta entity descriptor does not exist"))
        operation = data.get("operation")
        candidate = data.get("candidate")
        expected_hash = data.get("expected_item_hash")
        applied = str(data.get("delta_id")) in applied_delta_ids
        if not applied:
            unapplied_by_item.setdefault(str(data.get("item_id")), []).append(delta)
        if operation == "ADD":
            if expected_hash is not None or candidate is None:
                issues.append(Issue("DELTA_INVALID", delta.relative_path, "ADD requires null expected hash and a candidate"))
            if not applied and data.get("item_id") in catalog:
                issues.append(Issue("MAP_CONFLICT", delta.relative_path, "ADD targets an existing catalog item"))
        elif operation == "REPLACE":
            if expected_hash is None or candidate is None:
                issues.append(Issue("DELTA_INVALID", delta.relative_path, "REPLACE requires expected hash and candidate"))
        elif operation == "REMOVE":
            if expected_hash is None or candidate is not None:
                issues.append(Issue("DELTA_INVALID", delta.relative_path, "REMOVE requires expected hash and null candidate"))
        if isinstance(candidate, dict) and candidate.get("item_id") != data.get("item_id"):
            issues.append(Issue("DELTA_INVALID", delta.relative_path, "candidate item_id must equal delta item_id"))
        existing = catalog.get(data.get("item_id"))
        if applied:
            if operation in {"ADD", "REPLACE"}:
                candidate_hash = sha256_bytes(canonical_json_bytes(candidate)) if isinstance(candidate, dict) else None
                existing_hash = sha256_bytes(canonical_json_bytes(existing.data)) if existing is not None else None
                if candidate_hash is None or existing_hash != candidate_hash:
                    issues.append(Issue("APPLIED_DELTA_DRIFT", delta.relative_path, "catalog does not match applied candidate"))
            elif operation == "REMOVE" and existing is not None:
                issues.append(Issue("APPLIED_DELTA_DRIFT", delta.relative_path, "removed catalog item still exists"))
        elif operation in {"REPLACE", "REMOVE"}:
            if existing is None:
                issues.append(Issue("MAP_CONFLICT", delta.relative_path, "delta targets a missing catalog item"))
            elif sha256_bytes(canonical_json_bytes(existing.data)) != expected_hash:
                issues.append(Issue("MAP_CONFLICT", delta.relative_path, "expected item hash does not match catalog"))
        for evidence in data.get("evidence", []):
            if not _path_is_safe(str(evidence.get("path", ""))):
                issues.append(Issue("PATH_UNSAFE", delta.relative_path, f"unsafe evidence path {evidence.get('path')!r}"))

    for item_id, contenders in unapplied_by_item.items():
        if len(contenders) > 1:
            issues.append(
                Issue(
                    "DELTA_FORK",
                    contenders[0].relative_path,
                    f"{len(contenders)} unapplied deltas contend for catalog item {item_id}; serialize and rebase",
                )
            )

    known_delta_ids = {str(delta.data.get("delta_id")) for delta in _by_type(artifacts, "map_delta")}
    for delta_id in sorted(applied_delta_ids - known_delta_ids):
        issues.append(Issue("REFERENCE_MISSING", ".agentic_planning/reconciliations", f"applied delta {delta_id} does not exist"))

    for item in catalog.values():
        for evidence in item.data.get("evidence", []):
            if not _path_is_safe(str(evidence.get("path", ""))):
                issues.append(Issue("PATH_UNSAFE", item.relative_path, f"unsafe evidence path {evidence.get('path')!r}"))
        for relationship in item.data.get("relationships", []):
            if relationship.get("target_item_id") not in catalog:
                issues.append(Issue("REFERENCE_MISSING", item.relative_path, f"catalog target {relationship.get('target_item_id')} does not exist"))
        attribute_keys = [str(entry.get("key")) for entry in item.data.get("attributes", [])]
        if len(attribute_keys) != len(set(attribute_keys)):
            issues.append(Issue("CATALOG_INVALID", item.relative_path, "catalog attributes contain duplicate keys"))
    return issues


def _scope_overlaps(left: dict[str, Any], right: dict[str, Any]) -> bool:
    if left.get("repository_id") != right.get("repository_id"):
        return False
    left_path = str(left.get("path"))
    right_path = str(right.get("path"))
    left_tree = left.get("kind") == "tree"
    right_tree = right.get("kind") == "tree"
    if not left_tree and not right_tree:
        return left_path == right_path
    if left_tree and right_tree:
        return (
            left_path == right_path
            or left_path.startswith(right_path + "/")
            or right_path.startswith(left_path + "/")
        )
    tree_path, exact_path = (left_path, right_path) if left_tree else (right_path, left_path)
    return exact_path == tree_path or exact_path.startswith(tree_path + "/")


def _claims_compatible(left: dict[str, Any], right: dict[str, Any]) -> bool:
    if left.get("mode") == "read" and right.get("mode") == "read":
        return True
    if left.get("mode") == "isolated" and right.get("mode") == "isolated":
        return bool(left.get("isolation_key")) and left.get("isolation_key") != right.get("isolation_key")
    return False


def _active_manifests(artifacts: Sequence[Artifact]) -> list[Artifact]:
    descriptors = _by_type(artifacts, "entity_descriptor")
    events = _by_type(artifacts, "event")
    manifests = _by_type(artifacts, "entity_manifest")
    revisions = {item.data.get("revision_id"): item for item in manifests}
    descriptor_map = {str(item.data.get("entity_id")): item for item in descriptors}
    active: list[Artifact] = []
    for descriptor in descriptors:
        entity_id = str(descriptor.data.get("entity_id"))
        if _event_state(entity_id, events) in TERMINAL_STATES:
            continue
        current = _current_revision_id(entity_id, descriptor_map, manifests, events)
        if current in revisions:
            active.append(revisions[current])
    return sorted(active, key=lambda item: str(item.data.get("entity_id")))


def _repository_identity_issues(artifacts: Sequence[Artifact]) -> list[Issue]:
    """Ensure active coordinator-local manifest identities match the contract.

    A manifest may also pin product repositories outside the coordinator.  The
    coordinator repository is represented by its planning-base entry at ``.``;
    non-local scopes are permitted only when their repository identity is
    declared by one of the other planning-base entries.
    """
    contracts = _by_type(artifacts, "contract")
    if len(contracts) != 1:
        return []
    contract_repo_id = str(contracts[0].data["repo_id"])
    issues: list[Issue] = []
    for manifest in _active_manifests(artifacts):
        planning_base = manifest.data.get("planning_base", [])
        external_repository_ids = {
            str(base.get("repository_id"))
            for base in planning_base
            if base.get("path") != "."
        }
        for index, base in enumerate(planning_base):
            if base.get("path") == "." and base.get("repository_id") != contract_repo_id:
                issues.append(
                    Issue(
                        "BLOCKED_REPOSITORY_IDENTITY_CONFLICT",
                        manifest.relative_path,
                        f"planning_base[{index}].repository_id {base.get('repository_id')!r} "
                        f"does not match CONTRACT.repo_id {contract_repo_id!r}",
                    )
                )
        for index, scope in enumerate(manifest.data.get("write_scopes", [])):
            scope_repo_id = str(scope.get("repository_id"))
            if scope_repo_id == contract_repo_id or scope_repo_id in external_repository_ids:
                continue
            issues.append(
                Issue(
                    "BLOCKED_REPOSITORY_IDENTITY_CONFLICT",
                    manifest.relative_path,
                    f"write_scopes[{index}].repository_id {scope_repo_id!r} does not match "
                    f"CONTRACT.repo_id {contract_repo_id!r} or an external planning_base repository",
                )
            )
    return issues


def claim_issues(artifacts: Sequence[Artifact]) -> list[Issue]:
    active = _active_manifests(artifacts)
    issues: list[Issue] = []
    for index, left in enumerate(active):
        for right in active[index + 1 :]:
            left_id = str(left.data.get("entity_id"))
            right_id = str(right.data.get("entity_id"))
            if left_id == right_id:
                continue
            for left_scope in left.data.get("write_scopes", []):
                for right_scope in right.data.get("write_scopes", []):
                    if _scope_overlaps(left_scope, right_scope):
                        label = f"{left_scope.get('repository_id')}:{left_scope.get('path')} <> {right_scope.get('path')}"
                        issues.append(
                            Issue(
                                "WRITE_SCOPE_CONFLICT",
                                right.relative_path,
                                f"active entities {left_id} and {right_id} overlap at {label}",
                            )
                        )
            left_claims = {item.get("resource_id"): item for item in left.data.get("resource_claims", [])}
            right_claims = {item.get("resource_id"): item for item in right.data.get("resource_claims", [])}
            for resource_id in sorted(set(left_claims) & set(right_claims)):
                if not _claims_compatible(left_claims[resource_id], right_claims[resource_id]):
                    issues.append(
                        Issue(
                            "RESOURCE_BUSY",
                            right.relative_path,
                            f"active entities {left_id} and {right_id} have incompatible claims on {resource_id}",
                        )
                    )
    return sorted(set(issues))


def _protected_path_issues(artifacts: Sequence[Artifact]) -> list[Issue]:
    contracts = _by_type(artifacts, "contract")
    if len(contracts) != 1:
        return []
    contract = contracts[0]
    required = {
        ".agentic_planning/CONTRACT.json",
        ".agentic_planning/README.md",
        "WORKSPACE_MAP.md",
        ".agentic_planning/catalog/**",
        ".agentic_planning/reconciliations/**",
    }
    if contract.data.get("root_project_id") is not None:
        required.add("PROJECT_BLUEPRINT.md")
    managed_entry_points = contract.data.get("managed_entry_points", [])
    issues: list[Issue] = []
    for path in managed_entry_points:
        if not _path_is_safe(str(path)):
            issues.append(Issue("CONTRACT_INVALID", contract.relative_path, f"unsafe managed entry point {path!r}"))
        else:
            required.add(str(path))
    present = set(contract.data.get("protected_paths", []))
    missing = sorted(required - present)
    issues.extend(
        Issue("CONTRACT_INVALID", contract.relative_path, f"protected_paths is missing {path}")
        for path in missing
    )
    for manifest in _by_type(artifacts, "entity_manifest"):
        for scope in manifest.data.get("write_scopes", []):
            path = str(scope.get("path", ""))
            for protected in present:
                if _path_matches_pattern(path, protected) or (
                    scope.get("kind") == "tree" and _path_matches_pattern(protected.removesuffix("/**"), path + "/**")
                ):
                    issues.append(
                        Issue(
                            "PROTECTED_SCOPE",
                            manifest.relative_path,
                            f"ordinary write scope targets protected path {protected}",
                        )
                    )
                    break
    return issues


def validate_workspace(
    root: Path, explicit_paths: Sequence[str] | None = None, *, include_claims: bool = True
) -> tuple[list[Artifact], list[Issue]]:
    artifacts, issues = discover_artifacts(root, explicit_paths)
    schema_store = SchemaStore(Path(__file__).resolve().parent.parent / "schemas")
    for artifact in artifacts:
        issues.extend(
            schema_store.validate(
                artifact.data,
                SCHEMA_BY_ARTIFACT[artifact.expected_type],
                artifact.relative_path,
            )
        )
    if issues:
        return artifacts, sorted(set(issues))
    for artifact in artifacts:
        issues.extend(_identity_path_issues(artifact))
    issues.extend(_duplicate_id_issues(artifacts))
    issues.extend(_cross_reference_issues(artifacts))
    issues.extend(_repository_identity_issues(artifacts))
    issues.extend(_protected_path_issues(artifacts))
    if include_claims:
        issues.extend(claim_issues(artifacts))
    return artifacts, sorted(set(issues))


def _escape_markdown(value: Any) -> str:
    return str(value).replace("\\", "\\\\").replace("|", "\\|").replace("\r", " ").replace("\n", " ")


def render_index(contract: dict[str, Any], artifacts: Sequence[Artifact]) -> bytes:
    descriptors = _by_type(artifacts, "entity_descriptor")
    events = _by_type(artifacts, "event")
    manifests = _by_type(artifacts, "entity_manifest")
    manifests_by_revision = {str(item.data.get("revision_id")): item for item in manifests}
    descriptor_map = {str(item.data.get("entity_id")): item for item in descriptors}
    grouped = {kind: [] for kind in ENTITY_COLLECTION}
    for descriptor in descriptors:
        grouped[str(descriptor.data["kind"])].append(descriptor)
    lines = [
        "<!-- GENERATED BY RECONCILE_MAIN — DO NOT EDIT -->",
        "# Agentic Planning Index",
        "",
        f"Contract: v{contract['contract_version']}  ",
        f"Repository: `{contract['repo_id']}`",
        "",
    ]
    for kind, heading in (("feature", "Features"), ("analysis", "Analyses"), ("project", "Projects")):
        lines.extend(
            [
                f"## {heading}",
                "",
                "| ID | Title | Slug | State | Current revision | Planning base | Active claims | Sources | Registration | Owner |",
                "|---|---|---|---|---|---|---|---|---|---|",
            ]
        )
        ordered = sorted(
            grouped[kind],
            key=lambda item: (_datetime_key(item.data["created_at"]), item.data["entity_id"]),
        )
        if not ordered:
            lines.append("| — | — | — | — | — | — | — | — | — | — |")
        for descriptor in ordered:
            data = descriptor.data
            current_revision = _current_revision_id(str(data["entity_id"]), descriptor_map, manifests, events)
            manifest = manifests_by_revision.get(str(current_revision))
            planning_base = "—"
            claims = "—"
            if manifest is not None:
                planning_base = "; ".join(
                    f"{item['repository_id']}@{item['commit']}"
                    for item in sorted(
                        manifest.data.get("planning_base", []),
                        key=lambda item: (item["repository_id"], item["path"]),
                    )
                ) or "—"
                claims = "; ".join(
                    f"{item['resource_id']}:{item['mode']}"
                    + (f":{item['isolation_key']}" if item.get("isolation_key") else "")
                    for item in sorted(
                        manifest.data.get("resource_claims", []),
                        key=lambda item: item["resource_id"],
                    )
                ) or "—"
            sources = "; ".join(sorted(data.get("source_analysis_ids", []))) or "—"
            registration = next(
                (
                    str(event.data.get("reconciliation_receipt_id"))
                    for event in reversed(_event_chain(str(data["entity_id"]), events))
                    if event.data.get("event_type") == "RECONCILED"
                ),
                "—",
            )
            values = [
                f"`{data['entity_id']}`",
                data["title"],
                f"`{data['slug']}`",
                _event_state(data["entity_id"], events),
                f"`{current_revision}`" if current_revision else "—",
                planning_base,
                claims,
                sources,
                registration,
                data["owner"],
            ]
            lines.append("| " + " | ".join(_escape_markdown(value) for value in values) + " |")
        lines.append("")
    return ("\n".join(lines).rstrip() + "\n").encode("utf-8")


def _catalog_digest(catalog: Sequence[Artifact]) -> str:
    payload = b"".join(
        canonical_json_bytes(item.data)
        for item in sorted(catalog, key=lambda artifact: str(artifact.data["item_id"]))
    )
    return sha256_bytes(payload)


def render_workspace_map(contract: dict[str, Any], artifacts: Sequence[Artifact]) -> bytes:
    catalog = _by_type(artifacts, "catalog_item")
    by_kind = {kind: [] for kind in CATALOG_ORDER}
    for item in catalog:
        by_kind[str(item.data["kind"])].append(item)
    lines = [
        "<!-- GENERATED BY RECONCILE_MAIN — DO NOT EDIT -->",
        "# Workspace Map",
        "",
        "Planning-map contract: 4  ",
        f"Repository: `{contract['repo_id']}`  ",
        f"Catalog SHA-256: `{_catalog_digest(catalog)}`",
        "",
    ]
    for kind in CATALOG_ORDER:
        lines.extend(
            [
                f"## {CATALOG_HEADINGS[kind]}",
                "",
                "| Item ID | Title | Status | Summary | Attributes |",
                "|---|---|---|---|---|",
            ]
        )
        ordered = sorted(by_kind[kind], key=lambda item: (item.data["title"].casefold(), item.data["item_id"]))
        if not ordered:
            lines.append("| — | — | — | — | — |")
        for item in ordered:
            data = item.data
            attributes = "; ".join(
                f"{entry['key']}={json.dumps(entry['value'], ensure_ascii=False, sort_keys=True)}"
                for entry in sorted(data["attributes"], key=lambda entry: entry["key"])
            ) or "—"
            values = [
                f"`{data['item_id']}`",
                data["title"],
                data["status"],
                data["summary"],
                attributes,
            ]
            lines.append("| " + " | ".join(_escape_markdown(value) for value in values) + " |")
        lines.append("")
    return ("\n".join(lines).rstrip() + "\n").encode("utf-8")


def _root_blueprint_output(
    root: Path, contract: dict[str, Any], artifacts: Sequence[Artifact]
) -> tuple[tuple[Path, bytes] | None, list[Issue]]:
    root_project_id = contract.get("root_project_id")
    if root_project_id is None:
        return None, []
    descriptors = {
        str(item.data.get("entity_id")): item for item in _by_type(artifacts, "entity_descriptor")
    }
    descriptor = descriptors.get(str(root_project_id))
    if descriptor is None:
        return None, [Issue("REFERENCE_MISSING", ".agentic_planning/CONTRACT.json", f"root project {root_project_id} does not exist")]
    manifests = _by_type(artifacts, "entity_manifest")
    events = _by_type(artifacts, "event")
    revision_id = _current_revision_id(str(root_project_id), descriptors, manifests, events)
    if revision_id is None:
        return None, [Issue("REFERENCE_MISSING", descriptor.relative_path, "root project has no current revision")]
    manifest = next(
        (
            item
            for item in manifests
            if item.data.get("entity_id") == root_project_id
            and item.data.get("revision_id") == revision_id
        ),
        None,
    )
    if manifest is None:
        return None, [Issue("REFERENCE_MISSING", descriptor.relative_path, f"root revision {revision_id} has no manifest")]
    source = descriptor.path.parent / "plans" / revision_id / "PROJECT_BLUEPRINT.md"
    if not _under_root(root, source) or not source.is_file():
        return None, [Issue("REFERENCE_MISSING", _relative(root, source), "canonical root project blueprint does not exist")]
    try:
        source_bytes = source.read_bytes()
        source_bytes.decode("utf-8")
    except (OSError, UnicodeError) as exc:
        return None, [Issue("ARTIFACT_INVALID", _relative(root, source), f"blueprint is not readable UTF-8: {exc}")]
    source_relative = _relative(root, source)
    output = (
        "<!-- GENERATED BY RECONCILE_MAIN — DO NOT EDIT -->\n"
        "# Project Blueprint\n\n"
        "This file is a deterministic pointer to the immutable project source.\n\n"
        f"- Project: `{root_project_id}` — {_escape_markdown(descriptor.data['title'])}\n"
        f"- Revision: `{revision_id}`\n"
        f"- Manifest SHA-256: `{sha256_bytes(manifest.path.read_bytes())}`\n"
        f"- Canonical source: [`{source_relative}`](./{source_relative})\n"
        f"- Source SHA-256: `{sha256_bytes(source_bytes)}`\n"
    ).encode("utf-8")
    return (root / "PROJECT_BLUEPRINT.md", output), []


def _managed_block(target_relative: str, workspace_map_relative: str) -> bytes:
    parent = PurePosixPath(target_relative).parent.as_posix()
    start = "." if parent == "." else parent
    link = posixpath.relpath(workspace_map_relative, start=start)
    if not link.startswith("."):
        link = "./" + link
    lines = [
        MANAGED_BEGIN,
        "## Agentic planning routes",
        "",
        f"Read [`WORKSPACE_MAP.md`]({link}) before planning or implementation. ",
        "Ordinary work writes immutable entity sources only; it never edits the map, ",
        "global index or catalog. `PROMPT_RECONCILE_MAIN.md` is the exclusive global writer.",
        MANAGED_END,
    ]
    return ("\n".join(lines) + "\n").encode("utf-8")


def _managed_entry_output(
    root: Path, target_relative: str, workspace_map_relative: str
) -> tuple[tuple[Path, bytes] | None, list[Issue]]:
    if not _path_is_safe(target_relative):
        return None, [Issue("PATH_UNSAFE", ".agentic_planning/CONTRACT.json", f"unsafe managed entry point {target_relative!r}")]
    target = root / target_relative
    if not _under_root(root, target):
        return None, [Issue("PATH_OUTSIDE_ROOT", target_relative, "managed entry point is outside workspace")]
    try:
        current = target.read_bytes() if target.exists() else b""
        current.decode("utf-8")
    except (OSError, UnicodeError) as exc:
        return None, [Issue("ARTIFACT_INVALID", target_relative, f"managed entry point is not readable UTF-8: {exc}")]
    begin = MANAGED_BEGIN.encode("utf-8")
    end = MANAGED_END.encode("utf-8")
    begin_count = current.count(begin)
    end_count = current.count(end)
    block = _managed_block(target_relative, workspace_map_relative)
    if begin_count == 0 and end_count == 0:
        separator = b"" if not current or current.endswith(b"\n\n") else (b"\n" if current.endswith(b"\n") else b"\n\n")
        return (target, current + separator + block), []
    if begin_count != 1 or end_count != 1:
        return None, [Issue("MANAGED_BOUNDARY_INVALID", target_relative, "managed markers must occur exactly once as a pair")]
    begin_at = current.index(begin)
    end_at = current.index(end)
    if end_at < begin_at:
        return None, [Issue("MANAGED_BOUNDARY_INVALID", target_relative, "managed end marker precedes begin marker")]
    end_after = end_at + len(end)
    if end_after < len(current) and current[end_after : end_after + 2] == b"\r\n":
        end_after += 2
    elif end_after < len(current) and current[end_after : end_after + 1] == b"\n":
        end_after += 1
    return (target, current[:begin_at] + block + current[end_after:]), []


def expected_outputs(root: Path, artifacts: Sequence[Artifact]) -> tuple[dict[Path, bytes], list[Issue]]:
    contracts = _by_type(artifacts, "contract")
    if len(contracts) != 1:
        return {}, [Issue("CONTRACT_INVALID", ".agentic_planning/CONTRACT.json", "exactly one contract is required")]
    contract = contracts[0].data
    paths = contract["generated_views"]
    outputs: dict[Path, bytes] = {}
    for key, content in (
        ("index", render_index(contract, artifacts)),
        ("workspace_map", render_workspace_map(contract, artifacts)),
    ):
        target = root / paths[key]
        if not _under_root(root, target):
            return {}, [Issue("PATH_OUTSIDE_ROOT", str(paths[key]), "generated view is outside workspace")]
        outputs[target] = content
    issues: list[Issue] = []
    blueprint, blueprint_issues = _root_blueprint_output(root, contract, artifacts)
    issues.extend(blueprint_issues)
    if blueprint is not None:
        outputs[blueprint[0]] = blueprint[1]
    for target_relative in contract.get("managed_entry_points", []):
        managed, managed_issues = _managed_entry_output(
            root, str(target_relative), str(paths["workspace_map"])
        )
        issues.extend(managed_issues)
        if managed is not None:
            if managed[0] in outputs:
                issues.append(Issue("CONTRACT_INVALID", str(target_relative), "generated output paths must be unique"))
            else:
                outputs[managed[0]] = managed[1]
    return outputs, sorted(set(issues))


def _write_outputs_atomically(outputs: dict[Path, bytes]) -> None:
    staged: dict[Path, Path] = {}
    backups: dict[Path, Path] = {}
    replaced: list[Path] = []
    try:
        for target, content in outputs.items():
            target.parent.mkdir(parents=True, exist_ok=True)
            fd, raw_staged = tempfile.mkstemp(prefix=f".{target.name}.", suffix=".stage", dir=target.parent)
            staged_path = Path(raw_staged)
            with os.fdopen(fd, "wb") as handle:
                handle.write(content)
                handle.flush()
                os.fsync(handle.fileno())
            staged[target] = staged_path
            if target.exists():
                fd, raw_backup = tempfile.mkstemp(prefix=f".{target.name}.", suffix=".backup", dir=target.parent)
                os.close(fd)
                backup = Path(raw_backup)
                backup.write_bytes(target.read_bytes())
                backups[target] = backup
        for target in sorted(outputs, key=lambda path: path.as_posix()):
            os.replace(staged[target], target)
            replaced.append(target)
        for backup in backups.values():
            backup.unlink(missing_ok=True)
    except Exception:
        for target in reversed(replaced):
            backup = backups.get(target)
            if backup and backup.exists():
                os.replace(backup, target)
            else:
                target.unlink(missing_ok=True)
        raise
    finally:
        for path in [*staged.values(), *backups.values()]:
            path.unlink(missing_ok=True)


def _print_issues(issues: Sequence[Issue]) -> None:
    for issue in sorted(set(issues)):
        print(issue.line(), file=sys.stderr)


def _root_from_args(args: argparse.Namespace) -> Path:
    root = Path(args.root).resolve()
    if not root.is_dir():
        raise ValueError(f"workspace root does not exist: {root}")
    return root


def command_validate(args: argparse.Namespace) -> int:
    root = _root_from_args(args)
    artifacts, issues = validate_workspace(root, args.paths or None, include_claims=True)
    if issues:
        _print_issues(issues)
        return 1
    print(f"OK validate: {len(artifacts)} v3 artifacts")
    return 0


def command_claims(args: argparse.Namespace) -> int:
    root = _root_from_args(args)
    artifacts, issues = validate_workspace(root, include_claims=False)
    if not issues:
        issues = claim_issues(artifacts)
    if issues:
        _print_issues(issues)
        return 1
    active = _active_manifests(artifacts)
    print(f"OK claims: {len(active)} active manifests are compatible")
    return 0


def command_render(args: argparse.Namespace) -> int:
    root = _root_from_args(args)
    artifacts, issues = validate_workspace(root, include_claims=True)
    if issues:
        _print_issues(issues)
        return 1
    outputs, output_issues = expected_outputs(root, artifacts)
    if output_issues:
        _print_issues(output_issues)
        return 1
    if args.check:
        mismatches = []
        for target, expected in outputs.items():
            relative = _relative(root, target)
            if not target.is_file():
                mismatches.append(Issue("GENERATED_VIEW_MISSING", relative, "run render --write"))
            elif target.read_bytes() != expected:
                mismatches.append(Issue("GENERATED_VIEW_STALE", relative, "content differs from deterministic render"))
        if mismatches:
            _print_issues(mismatches)
            return 1
        print(f"OK render --check: {len(outputs)} generated views are current")
        return 0
    _write_outputs_atomically(outputs)
    for target in sorted(outputs, key=lambda path: path.as_posix()):
        print(f"WROTE {_relative(root, target)} {sha256_bytes(outputs[target])}")
    return 0


def _path_matches_pattern(path: str, pattern: str) -> bool:
    normalized = path.replace("\\", "/").lstrip("./")
    target = pattern.replace("\\", "/").lstrip("./")
    if target.endswith("/**"):
        prefix = target[:-3].rstrip("/")
        return normalized == prefix or normalized.startswith(prefix + "/")
    return normalized == target


def _git(root: Path, arguments: Sequence[str]) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        ["git", *arguments],
        cwd=root,
        text=True,
        encoding="utf-8",
        errors="replace",
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        check=False,
    )


def _git_changed_paths(root: Path, base: str) -> tuple[set[str], list[Issue]]:
    verify = _git(root, ["rev-parse", "--verify", f"{base}^{{commit}}"])
    if verify.returncode != 0:
        return set(), [Issue("GIT_BASE_INVALID", base, verify.stderr.strip() or "base is not a commit")]
    commands = [
        ["diff", "--name-only", "--diff-filter=ACDMRTUXB", f"{base}...HEAD"],
        ["diff", "--name-only", "--diff-filter=ACDMRTUXB"],
        ["diff", "--cached", "--name-only", "--diff-filter=ACDMRTUXB"],
        ["ls-files", "--others", "--exclude-standard"],
    ]
    changed: set[str] = set()
    for command in commands:
        result = _git(root, command)
        if result.returncode != 0:
            return set(), [Issue("GIT_DIFF_FAILED", ".", result.stderr.strip() or "git diff failed")]
        changed.update(line.strip().replace("\\", "/") for line in result.stdout.splitlines() if line.strip())
    return changed, []


def _exists_at_git_ref(root: Path, git_ref: str, path: str) -> bool:
    result = _git(root, ["ls-tree", "-r", "--name-only", git_ref, "--", path])
    return result.returncode == 0 and path in {line.strip() for line in result.stdout.splitlines()}


def _scope_covers(path: str, scope: dict[str, Any]) -> bool:
    scope_path = str(scope.get("path", ""))
    if scope.get("kind") == "exact":
        return path == scope_path
    return path == scope_path or path.startswith(scope_path + "/")


def _candidate_scope_issues(
    root: Path,
    base: str,
    changed: set[str],
    artifacts: Sequence[Artifact],
    protected_patterns: Sequence[str],
) -> list[Issue]:
    issues: list[Issue] = []
    ignored = _git(
        root,
        ["ls-files", "--others", "--ignored", "--exclude-standard", "--", ".agentic_planning"],
    )
    if ignored.returncode == 0:
        for ignored_path in sorted(line.strip().replace("\\", "/") for line in ignored.stdout.splitlines() if line.strip()):
            if "/.local/" not in ignored_path and not ignored_path.startswith(".agentic_planning/.local/"):
                issues.append(
                    Issue(
                        "PLANNING_SOURCE_IGNORED",
                        ignored_path,
                        "canonical planning files must be force-included by the repository .gitignore",
                    )
                )
    entity_ids: set[str] = set()
    product_paths: list[str] = []
    entity_source = re.compile(r"^\.agentic_planning/(features|analyses|projects)/([^/]+)/(.+)$")
    for path in sorted(changed):
        if any(_path_matches_pattern(path, pattern) for pattern in protected_patterns):
            continue
        match = entity_source.match(path)
        if match:
            entity_dir = match.group(2)
            entity_id = entity_dir.split("--", 1)[0]
            if not re.match(r"^(ftr|ana|prj)_[0-9a-f-]+$", entity_id):
                issues.append(Issue("ENTITY_PATH_INVALID", path, "entity directory has no valid prefixed identity"))
                continue
            entity_ids.add(entity_id)
            current = root / path
            if not current.is_file():
                issues.append(Issue("IMMUTABLE_SOURCE_DELETED", path, "entity-owned sources are create-only"))
            elif _exists_at_git_ref(root, base, path):
                issues.append(Issue("IMMUTABLE_SOURCE_CHANGED", path, "existing entity-owned source was modified"))
            continue
        if path.startswith(".agentic_planning/"):
            issues.append(Issue("PLANNING_PATH_UNOWNED", path, "path is neither an entity-owned source nor an authorized protected output"))
            continue
        product_paths.append(path)

    descriptors = {
        str(item.data.get("entity_id")): item for item in _by_type(artifacts, "entity_descriptor")
    }
    manifests = _by_type(artifacts, "entity_manifest")
    events = _by_type(artifacts, "event")
    manifests_by_revision = {str(item.data.get("revision_id")): item for item in manifests}
    contract = _by_type(artifacts, "contract")[0].data
    local_repo_id = str(contract["repo_id"])
    scopes: list[tuple[str, dict[str, Any]]] = []
    for entity_id in sorted(entity_ids):
        revision_id = _current_revision_id(entity_id, descriptors, manifests, events)
        manifest = manifests_by_revision.get(str(revision_id))
        if manifest is None or manifest.data.get("entity_id") != entity_id:
            issues.append(Issue("SCOPE_OWNER_INVALID", entity_id, "changed entity has no current manifest"))
            continue
        for scope in manifest.data.get("write_scopes", []):
            if scope.get("repository_id") == local_repo_id:
                scopes.append((entity_id, scope))

    for path in product_paths:
        if not entity_ids:
            issues.append(Issue("SCOPE_OWNER_MISSING", path, "product change has no changed entity-owned receipt/event/source"))
            continue
        if not any(_scope_covers(path, scope) for _, scope in scopes):
            owners = ", ".join(sorted(entity_ids))
            issues.append(Issue("WRITE_SCOPE_VIOLATION", path, f"not covered by current manifest scopes for {owners}"))
    return issues


def _catalog_change_issues(
    root: Path,
    base: str,
    changed: set[str],
    artifacts: Sequence[Artifact],
    catalog_path: str,
) -> list[Issue]:
    applied_ids = {
        str(delta_id)
        for receipt in _by_type(artifacts, "reconciliation_receipt")
        if receipt.data.get("status") == "SUCCEEDED"
        for delta_id in receipt.data.get("applied_delta_ids", [])
    }
    deltas = [
        item
        for item in _by_type(artifacts, "map_delta")
        if str(item.data.get("delta_id")) in applied_ids
    ]
    issues: list[Issue] = []
    prefix = catalog_path.rstrip("/") + "/"
    for path in sorted(item for item in changed if item.startswith(prefix) and item.endswith(".json")):
        item_id = PurePosixPath(path).stem
        existed = _exists_at_git_ref(root, base, path)
        exists = (root / path).is_file()
        operation = "REPLACE" if existed and exists else "ADD" if exists else "REMOVE"
        matches = [
            delta
            for delta in deltas
            if delta.data.get("item_id") == item_id and delta.data.get("operation") == operation
        ]
        if len(matches) != 1:
            issues.append(
                Issue(
                    "CATALOG_CHANGE_UNATTRIBUTED",
                    path,
                    f"{operation} requires exactly one successfully applied map delta for {item_id}",
                )
            )
    return issues


def command_protected(args: argparse.Namespace) -> int:
    root = _root_from_args(args)
    artifacts, issues = validate_workspace(root, include_claims=True)
    if issues:
        _print_issues(issues)
        return 1
    contract_artifacts = _by_type(artifacts, "contract")
    contract = contract_artifacts[0].data
    changed, git_issues = _git_changed_paths(root, args.base)
    if git_issues:
        _print_issues(git_issues)
        return 1
    protected_patterns = contract["protected_paths"]
    protected_changed = sorted(
        path for path in changed if any(_path_matches_pattern(path, pattern) for pattern in protected_patterns)
    )
    scope_issues = _candidate_scope_issues(root, args.base, changed, artifacts, protected_patterns)
    if scope_issues:
        _print_issues(scope_issues)
        return 1
    if not protected_changed:
        print("OK protected: immutable sources and product scopes are valid; no protected global paths changed")
        return 0
    if not args.integration:
        _print_issues(
            [
                Issue("PROTECTED_PATH_CHANGED", path, "ordinary branches cannot modify this global path")
                for path in protected_changed
            ]
        )
        return 1

    catalog_issues = _catalog_change_issues(
        root, args.base, changed, artifacts, str(contract["catalog_path"])
    )
    if catalog_issues:
        _print_issues(catalog_issues)
        return 1

    outputs, output_issues = expected_outputs(root, artifacts)
    generated = {_relative(root, target) for target in outputs}
    catalog_pattern = contract["catalog_path"] + "/**"
    unsupported = [
        path
        for path in protected_changed
        if path not in generated
        and not _path_matches_pattern(path, catalog_pattern)
        and re.fullmatch(r"\.agentic_planning/reconciliations/rec_[0-9a-f-]+/receipt\.json", path) is None
    ]
    if unsupported:
        _print_issues(
            [
                Issue("INTEGRATION_PATH_UNSUPPORTED", path, "control plane cannot prove this protected edit")
                for path in unsupported
            ]
        )
        return 1
    for target, expected in outputs.items():
        relative = _relative(root, target)
        if not target.is_file() or target.read_bytes() != expected:
            output_issues.append(
                Issue("GENERATED_VIEW_STALE", relative, "integration view must exactly match deterministic render")
            )
    if output_issues:
        _print_issues(output_issues)
        return 1
    print(f"OK protected --integration: {len(protected_changed)} protected changes are reproducible")
    return 0


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Agentic Planning Kit v3 deterministic control plane"
    )
    parser.add_argument("--version", action="version", version=TOOL_VERSION)
    subparsers = parser.add_subparsers(dest="command", required=True)

    validate_parser = subparsers.add_parser("validate", help="validate schemas, IDs, references, events, paths, and active claims")
    validate_parser.add_argument("--root", default=".", help="workspace root (default: current directory)")
    validate_parser.add_argument("paths", nargs="*", help="optional artifact paths; omit for the complete workspace")
    validate_parser.set_defaults(handler=command_validate)

    claims_parser = subparsers.add_parser("claims", help="check active write scopes and resource claims")
    claims_parser.add_argument("--root", default=".", help="workspace root (default: current directory)")
    claims_parser.set_defaults(handler=command_claims)

    render_parser = subparsers.add_parser("render", help="render generated index and workspace map")
    render_parser.add_argument("--root", default=".", help="workspace root (default: current directory)")
    render_mode = render_parser.add_mutually_exclusive_group(required=True)
    render_mode.add_argument("--check", action="store_true", help="fail if generated views differ")
    render_mode.add_argument("--write", action="store_true", help="replace generated views from validated sources")
    render_parser.set_defaults(handler=command_render)

    protected_parser = subparsers.add_parser("protected", help="enforce the protected global-path policy against a Git base")
    protected_parser.add_argument("--root", default=".", help="workspace root (default: current directory)")
    protected_parser.add_argument("--base", required=True, help="Git commit/ref used as the comparison base")
    protected_parser.add_argument(
        "--integration",
        action="store_true",
        help="allow catalog changes and exact deterministic generated views for RECONCILE_MAIN",
    )
    protected_parser.set_defaults(handler=command_protected)
    return parser


def main(argv: Sequence[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)
    try:
        return int(args.handler(args))
    except (OSError, ValueError) as exc:
        print(f"ERROR CONTROL_PLANE_FAILED .: {exc}", file=sys.stderr)
        return 2


if __name__ == "__main__":
    raise SystemExit(main())
